name: Docker Extract

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  extract:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_EXTRACT }}
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: ghcr.io/${{ github.repository }}:latest
          path: /CV/main.pdf/.
      - name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: main.pdf
