name: Docker Extract Login

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  extract:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Get PTF in Docker
        run: |
          docker build --tag my_image -f Dockerfile .
          docker create --name my_cont my_image
          docker start my_cont
          docker cp my_cont:/CV/main.pdf .
        
      - uses: actions/upload-artifact@v2
        with:
          name: CV
          path: ./main.pdf

      - uses: actions/download-artifact@v2
        with:
          name: CV
