name: Docker Extract Login

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  extract:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Get PDF
        run: |
          docker build --tag my_image -f Dockerfile .
          docker create --name my_cont my_image
          docker start my_cont
          docker cp my_cont:/CV/main.pdf .
      

      - name: Prepare PDF for upload
        run: |
          mkdir artifacts/ && \
          mv main.pdf artifacts/resume.pdf


      - name: Upload PDF as artifact
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: artifacts/
          publish_branch: pdf
          force_orphan: true
